[en]
  title = "Home"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

[ja]
  title = "Home"
  languageName = "日本語"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ja"
